# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YunpianService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=128, verbose_name='API-KEY')),
            ],
            options={
                'verbose_name': '云片短信通道',
                'verbose_name_plural': '云片短信通道',
            },
        ),
    ]
