# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-25 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=32, verbose_name='手机号')),
                ('birthday', models.DateField(auto_now=True, verbose_name='生日')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.IntegerField(choices=[(1, 'man'), (2, 'woman')], default=1, verbose_name='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户关联表',
                'verbose_name_plural': '用户关联表',
            },
        ),
    ]
