# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pn',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号'),
        ),
    ]
